// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1:string):Promise<boolean>;

export function GetVideoInfo(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
