// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateClip(arg1, arg2, arg3, arg4) {
  return window['go']['ffmpeg']['FFmpeg']['CreateClip'](arg1, arg2, arg3, arg4);
}

export function DefaultParams() {
  return window['go']['ffmpeg']['FFmpeg']['DefaultParams']();
}

export function GetParams() {
  return window['go']['ffmpeg']['FFmpeg']['GetParams']();
}

export function SetParams(arg1) {
  return window['go']['ffmpeg']['FFmpeg']['SetParams'](arg1);
}
