// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ffmpeg} from '../models';

export function CreateClip(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DefaultParams():Promise<Array<string>>;

export function GetParams():Promise<Array<string>>;

export function GetVideoInfo(arg1:string):Promise<ffmpeg.VideoInfo>;

export function SetParams(arg1:string):Promise<void>;
